[book]
authors = ["Evil Martians"]
language = "en"
multilingual = false
src = "docs/mdbook"
title = "Hookflow Documentation"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/tekintian/hookflow"

[output.html.fold]
enable = true
